---
    name: trivy-iac-scan-tf 
    on:
      pull_request:
        types: [ opened, reopened, synchronize ]
        paths:
        #   - "**/*.tf"
        #   - "**/*.tfvars"
    
      push:
        branches:
          - main
        paths:
        #   - "**/*.tf"
        #   - "**/*.tfvars"
    
    jobs:
      trivy:
        name: tfsec-SAST-check-report
        runs-on: ubuntu-latest
    
        steps:
          - name: Clone repo
            uses: actions/checkout@main
    
          - name: Run Trivy vulnerability scanner in IaC mode
            id: trivy
            uses: aquasecurity/trivy-action@master
            with:
              scan-type: 'config'
              hide-progress: false
              format: 'sarif'
              output: 'trivy-results.sarif'
              #exit-code: '1'
              ignore-unfixed: true
              trivy-config: 'trivy-config.yaml'
          
          - name: Reviewdog comment IAC checks
            id: reviewdog-trivy-iac
            uses: reviewdog/action-setup@v1
            env:
              REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              reviewdog_version: latest
            run: |
                reviewdog -f=sarif -diff="git diff" -reporter=github-pr-check -level=WARNING
    